theme = "gruvbox_custom"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
bufferline = "multiple"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["diagnostics"]
right = ["position", "file-encoding", "file-type"]
separator = "│"

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
"L" = "goto_next_buffer"
"H" = "goto_previous_buffer"

[keys.normal.space]
"w" = ":w"
"q" = ":q"
